from colorama import init , Fore , Back , Style
init()

print(Fore.BLACK + 'BLACK')
print(Fore.RED + 'RED')
print(Fore.CYAN + 'CYAN')
print(Fore.GREEN + 'GREEN')
print(Fore.YELLOW + 'YELLOW')
print(Fore.BLUE  + 'BLUE')
print(Fore.MAGENTA + 'MAGENTA')
print(Fore.CYAN + 'CYAN')
print(Fore.WHITE + 'WHITE')
print(Fore.LIGHTBLACK_EX + 'LIGHTBLACK_EX')
print(Fore.LIGHTRED_EX + 'LIGHTRED_EX')
print(Fore.LIGHTGREEN_EX + 'LIGHTGREEN_EX')
print(Fore.LIGHTYELLOW_EX + 'LIGHTYELLOW_EX')
print(Fore.LIGHTBLUE_EX + 'LIGHTBLUE_EX')
print(Fore.LIGHTMAGENTA_EX + 'LIGHTMAGENTA_EX')
print(Fore.LIGHTCYAN_EX + 'LIGHTCYAN_EX')
print(Fore.LIGHTWHITE_EX + 'LIGHTWHITE_EX')

print(Back.BLACK + 'BLACK')
print(Back.BLUE + 'BLUE')
print(Back.CYAN + 'CYAN')
print(Back.GREEN + 'GREEN')
print(Back.LIGHTBLUE_EX + 'LIGHTBLUE_EX')
print(Back.LIGHTCYAN_EX + 'LIGHTCYAN_EX')
print(Back.LIGHTMAGENTA_EX + 'LIGHTMAGENTA_EX')
print(Back.LIGHTWHITE_EX + 'LIGHTWHITE_EX')
print(Back.LIGHTYELLOW_EX + 'LIGHTYELLOW_EX')
print(Back.YELLOW + 'YELLOW')
print(Back.MAGENTA + 'MAGENTA')
print(Back.RED + 'MAGENTA')


